### PR TITLE
accessories landing page styling

### LINKED ISSUE #48: [content] Accessories Category
populate languages for accessories content (placeholders)

### PR DESCRIPTION
**Pull request by dkuntze**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #48

Test URLs:
- Before: https://main--airlessco--hlxsites.hlx.page/na/en/products/accessories/
- After:  https://issue-48--airlessco--hlxsites.hlx.page/na/en/products/accessories/

### CODE REVIEW

**Review by bstopp — COMMENTED** [review]
Two questions: 

can we merge this logic with the stuff on the [product cards](https://github.com/hlxsites/airlessco/blob/844f40eb9d8269cab6be8952b59ddf23465a640e/blocks/productcards/productcards.css#L20) So we only have one place to tag "hey wrap this content in a div and style the product information like this".

And if that's possible, can it be pushed down the styles.css file to after the element defintions to where class' are used?

I order the file:

element
...
class

Goes least -> most specifica

**Comment by dkuntze** [comment]
sure. Its styling an OOTB block (Columns) - I figured by that context it should go in the general styles.css

**Comment by bstopp** [comment]
Hm. Product Cards is based on the individual anchors within the flexbox. So wondering if there's a way to pull that off across all contexts.

**Comment by dkuntze** [comment]
Maybe - but I think that is additional exercise.

**Review by bstopp — APPROVED** [review]

**Review by bstopp — APPROVED** [review]

**Pull request merged**
