### PR TITLE
Issue 21

### PR DESCRIPTION
**Pull request by helms-charity**
Fix issue #21 

Test URLs:
Before: https://main--airlessco--hlxsites.hlx.page/na/en/products/
after: https://issue-21--airlessco--hlxsites.hlx.page/na/en/products/

### CODE REVIEW

**Comment by helms-charity** [comment]
I seem to have poisoned the FCP score...

**Review by dkuntze — CHANGES_REQUESTED** [review]
re-add sortable js

**Comment by helms-charity** [comment]
BAD:
Before: https://main--airlessco--hlxsites.hlx.page/na/en/footer
After: https://issue-21--airlessco--hlxsites.hlx.page/
GOOD:
Before: https://main--airlessco--hlxsites.hlx.page/na/en/products/
after: https://issue-21--airlessco--hlxsites.hlx.page/na/en/products/

**Comment by helms-charity** [comment]
Ready for review -- the sortable.js says it is empty when viewing the diff, but if you click through to view file, it is untouched.

**Comment by dkuntze** [comment]
@venturewise the images are squished at full width browser size:

image

**Review by dkuntze — APPROVED** [review]

**Pull request merged**
